import os

ENTRYPOINT_WS_ENABLED = os.getenv('ENTRYPOINT_WS_ENABLED', '0') == '1'
ENTRYPOINT_WS_SERVICE_HOST = os.getenv('ENTRYPOINT_WS_SERVICE_HOST', '0.0.0.0')
ENTRYPOINT_WS_SERVICE_DEBUG = os.getenv('ENTRYPOINT_WS_SERVICE_DEBUG', 'False') == 'True'
ENTRYPOINT_WS_SERVICE_PORT = os.getenv('ENTRYPOINT_WS_SERVICE_PORT', 8001)
ENTRYPOINT_WS_SERVICE_LOG_LEVEL = os.getenv('ENTRYPOINT_WS_SERVICE_LOG_LEVEL', 'info')

ENTRYPOINT_WS_SERVICE_CONFIG = {"bollydog.entrypoint.websocket.app.SocketService": {}} if ENTRYPOINT_WS_ENABLED else {}
