import os

SERVICE_HOST = os.getenv('BOLLYDOG_HTTP_SERVICE_HOST', '0.0.0.0')
SERVICE_DEBUG = os.getenv('BOLLYDOG_HTTP_SERVICE_DEBUG', 'False') == 'True'
SERVICE_PORT = os.getenv('BOLLYDOG_HTTP_SERVICE_PORT', 8000)
SERVICE_LOG_LEVEL = os.getenv('BOLLYDOG_HTTP_SERVICE_LOG_LEVEL', 'info')

# SERVICE_SECRET_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_SECRET_KEY', 'KFC-CRAZY-THURSDAY-VME-50')

SERVICE_PRIVATE_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_PRIVATE_KEY', None)
SERVICE_PUBLIC_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_PUBLIC_KEY', None)
SERVICE_PRIVATE_KEY_PATH = os.getenv('BOLLYDOG_HTTP_SERVICE_PRIVATE_KEY_PATH', None)
SERVICE_PUBLIC_KEY_PATH = os.getenv('BOLLYDOG_HTTP_SERVICE_PUBLIC_KEY_PATH', None)
