import os

ENTRYPOINT_HTTP_SERVICE_HOST = os.getenv('ENTRYPOINT_HTTP_SERVICE_HOST', '0.0.0.0')
ENTRYPOINT_HTTP_SERVICE_DEBUG = os.getenv('ENTRYPOINT_HTTP_SERVICE_DEBUG', 'False') == 'True'
ENTRYPOINT_HTTP_SERVICE_PORT = os.getenv('ENTRYPOINT_HTTP_SERVICE_PORT', 8000)
ENTRYPOINT_HTTP_SERVICE_LOG_LEVEL = os.getenv('ENTRYPOINT_HTTP_SERVICE_LOG_LEVEL', 'info')

ENTRYPOINT_HTTP_SERVICE_PRIVATE_KEY = os.getenv('ENTRYPOINT_HTTP_SERVICE_PRIVATE_KEY', None)
ENTRYPOINT_HTTP_SERVICE_PUBLIC_KEY = os.getenv('ENTRYPOINT_HTTP_SERVICE_PUBLIC_KEY', None)
ENTRYPOINT_HTTP_SERVICE_PRIVATE_KEY_PATH = os.getenv('ENTRYPOINT_HTTP_SERVICE_PRIVATE_KEY_PATH', None)
ENTRYPOINT_HTTP_SERVICE_PUBLIC_KEY_PATH = os.getenv('ENTRYPOINT_HTTP_SERVICE_PUBLIC_KEY_PATH', None)

ENTRYPOINT_HTTP_SERVICE_LOOP = os.getenv('ENTRYPOINT_HTTP_SERVICE_LOOP', 'uvloop')
ENTRYPOINT_HTTP_SERVICE_HTTP = os.getenv('ENTRYPOINT_HTTP_SERVICE_HTTP', 'httptools')
ENTRYPOINT_HTTP_SERVICE_LIMIT_CONCURRENCY = int(os.getenv('ENTRYPOINT_HTTP_SERVICE_LIMIT_CONCURRENCY', 0)) or None
ENTRYPOINT_HTTP_SERVICE_LIMIT_MAX_REQUESTS = int(os.getenv('ENTRYPOINT_HTTP_SERVICE_LIMIT_MAX_REQUESTS', 2000))
ENTRYPOINT_HTTP_SERVICE_TIMEOUT_KEEP_ALIVE = int(os.getenv('ENTRYPOINT_HTTP_SERVICE_TIMEOUT_KEEP_ALIVE', 5))
ENTRYPOINT_HTTP_SERVICE_BACKLOG = int(os.getenv('ENTRYPOINT_HTTP_SERVICE_BACKLOG', 128))

ENTRYPOINT_HTTP_MIDDLEWARE_SESSION = os.getenv('ENTRYPOINT_HTTP_MIDDLEWARE_SESSION', '1') == '1'
ENTRYPOINT_HTTP_MIDDLEWARE_AUTH = os.getenv('ENTRYPOINT_HTTP_MIDDLEWARE_AUTH', '1') == '1'
ENTRYPOINT_HTTP_MIDDLEWARE_CORS = os.getenv('ENTRYPOINT_HTTP_MIDDLEWARE_CORS', '1') == '1'
ENTRYPOINT_HTTP_MIDDLEWARE_SESSIONS_SECRET_KEY = os.getenv('ENTRYPOINT_HTTP_MIDDLEWARE_SESSIONS_SECRET_KEY', '')
